@extends('layout')
@section('content')
    <x-content::gallery
        :galleryId="$data['promo-slider']"
        defaultTemplate="slider"
    />
    <x-content::gallery
        :galleryId="$data['cards']"
        defaultTemplate="cards"
    />
@endsection
